project_id = "efjuxymqntahxtibpqwh"

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.test-evolution-connection]
verify_jwt = false

[functions.evolution-get-qrcode]
verify_jwt = false

[functions.process-order-payment]
verify_jwt = false


